
services:
  db:
    container_name: mysql_container
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    command: ["mysqld", "--mysql-native-password=ON"]
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD" ]
      retries: 5
      interval: 10s
      start_period: 30s
      timeout: 10s

  app:
    container_name: lab_backend
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}

    depends_on:
      db:
        condition: service_healthy

    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
