name: labs_backend
services:
  server_app:
    container_name: backend
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

    environment:
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}

    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: postgres_container
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10

