openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /upload:
    post:
      summary: Upload File
      operationId: upload_file_upload_post
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_upload_file_upload_post'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Body_upload_file_upload_post:
      properties:
        file:
          type: string
          format: binary
          title: File
        lab_name:
          $ref: '#/components/schemas/LabName'
      type: object
      required:
      - file
      - lab_name
      title: Body_upload_file_upload_post
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    LabName:
      type: string
      enum:
      - sql_injection_lab
      - broken_access_control_lab
      - cryptographic_failures_lab
      title: LabName
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
